_target_: atria_datasets.layout_analysis.doclaynet.DocLayNet
_partial_: false
dataset_name: doclaynet
config_name: 1k
max_train_samples: 1000
max_validation_samples: 1000
max_test_samples: null
hf_repo: ds4sd/DocLayNet
hf_config_name: '2022.08'
