_target_: atria_datasets.vqa.due.DueBenchmarkExtractiveQA
_partial_: false
dataset_name: due_benchmark
config_name: ExKleisterCharity
max_train_samples: null
max_validation_samples: null
max_test_samples: null
segment_levels:
- tokens
- pages
ocr_engine: microsoft_cv
answers_extraction_method: v1
image_dpi: 72
