_target_: atria_datasets.language_modeling.due.DueBenchmark
_partial_: false
dataset_name: due_benchmark
config_name: PWC
max_train_samples: null
max_validation_samples: null
max_test_samples: null
model_path: google-t5/t5-large
model_type: t5
use_fast_tokenizer: true
max_encoder_length: 1024
unescape_prefix: false
unescape_values: true
use_prefix: true
prefix_separator: ':'
values_separator: '|'
single_property: true
use_none_answers: false
limit: -1
case_augmentation: false
segment_levels:
- tokens
- pages
long_page_strategy: FIRST_PART
ocr_engine: tesseract
lowercase_expected: false
lowercase_input: false
train_strategy: concat
dev_strategy: concat
test_strategy: concat
augment_tokens_from_file: ''
img_matrix_order: 0
processes: 1
imap_chunksize: 100
skip_text_tokens: false
