_target_: atria_datasets.layout_analysis.publaynet.PubLayNet
_partial_: false
dataset_name: publaynet
config_name: 1k
max_train_samples: 1000
max_validation_samples: null
max_test_samples: null
hf_repo: jordanparker6/publaynet
hf_config_name: default
